backend:
  name: github
  repo: SamWolfs/asist-knowledge-center
  branch: main
media_folder: static/assets
public_folder: /assets
publish_mode: editorial_workflow
collections:
  - name: open-source
    label: Open Source
    folder: content/open-source
    create: true
    fields:
      - { name: title, label: Title }
      - { name: metaTitle, label: Meta Title }
      - { name: metaDescription, label: Meta Description }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }
  - name: tooling
    label: Tooling
    folder: content/tooling
    create: true
    fields:
      - { name: title, label: Title }
      - { name: metaTitle, label: Meta Title }
      - { name: metaDescription, label: Meta Description }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }
  - name: web-development
    label: Web Development
    folder: content/web-development
    create: true
    fields:
      - { name: title, label: Title }
      - { name: metaTitle, label: Meta Title }
      - { name: metaDescription, label: Meta Description }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }
